export default{
    yunshi_arr:[
        {
            test:'CaiYun',
            str:'财运指数',
            weak_arr:['星期一','星期二','星期三','星期四','星期五','星期六','星期日'],
            weak_arr:['星期一','星期二','星期三','星期四','星期五','星期六','星期日']
        },
        {
            test:'ShiYeYun',
            str:'事业指数',
            weak_arr:['星期一','星期二','星期三','星期四','星期五','星期六','星期日']
        },
        {
            test:'YinYuanYun',
            str:'姻缘指数',
            weak_arr:['星期一','星期二','星期三','星期四','星期五','星期六','星期日']
        },
        
        {
            test:'ShiXiang',
            str:'事项'
        },
        {
            test:'TianGan',
            str:'天干',
            toarr:','
        },
        {
            test:'XingYun',
            str:'星运',
            toarr:','
        },
        {
            test:'CangGan',
            str:'藏干',
            toarr:','
        },
        
        {
            test:'ShenSha',
            str:'神煞',
            toarr:';'
        },
        {
            test:'ZhuXing',
            str:'主星',
            toarr:','
        },
        {
            test:'XinXingShiXiang',
            str:'心性事项'
        },
        {
            test:'GongLi',
            str:'公历'
        },
        {
            test:'NongLi',
            str:'农历'
        },
        {
            test:'GanZhi',
            str:'干支'
        },
        {
            test:'WeekDay',
            str:'日期'
        },
        {
            test:'TotalShiYeYun',
            str:'事业运总结'
        },
        {
            test:'Date',
            str:'日期（农历和公历）'
        },
        {
            test:'Desc',
            str:'简介'
        },
        {
            test:'TotalYinYuanYun',
            str:'姻缘运总结'
        },
        {
            test:'Yun',
            str:'运',
            weak_arr:['星期一','星期二','星期三','星期四','星期五','星期六','星期日']
        },
        {
            test:'WeekdayOffset',
            str:'工作指数',
            weak_arr:['星期一','星期二','星期三','星期四','星期五','星期六','星期日']
        },
        {
            test:'TotalCaiYun',
            str:'财运总结'
        },
        {
            test:'CengCiDuanYu',
            str:'层次'
        },
        {
            test:'CengCiZhiShu',
            str:'层次指数'
        },
        {
            test:'YuanFenDuanYu',
            str:'缘分'
        },
        {
            test:'YuanFenZhiShu',
            str:'缘分指数'
        },
        {
            test:'ZhuYiDuanYu',
            str:'助益'
        },
        {
            test:'ZhuYiZhiShu',
            str:'助益指数'
        },
        {
            test:'ZiNuDuanYu',
            str:'子女'
        },
        {
            test:'ZiNuZhiShu',
            str:'子女数量'
        },
        {
            test:'ZongHeDuanYu',
            str:'综合'
        },
        {
            test:'ZongHeZhiShu',
            str:'综合指数'
        },
        // {
        //     test:'name',
        //     str:'星座'
        // },
        {
            test:'astrology',
            str:'星座'
        },
        {
            test:'birthday',
            str:'生日'
        },
        {
            test:'dizhihechong',
            str:'地支和冲'
        },
        {
            test:'dzSanHui',
            str:'地支三会'
        },
        {
            test:'dzXiangXing',
            str:'地支相性'
        },
        {
            test:'huo',
            str:'火'
        },
        {
            test:'jiaoyunshijian',
            str:'交运时间'
        },
        {
            test:'jieqi',
            str:'节气'
        },
        {
            test:'jin',
            str:'进'
        },
        {
            test:'jishen',
            str:'晋升'
        },
        {
            test:'kongwang',
            str:'空亡',
            
        },
        {
            test:'liutong',
            str:'流通'
        },
        {
            test:'lunar',
            str:'农历生日'
        },
        {
            test:'minggong',
            str:'周'
        },
        {
            test:'mu',
            str:'木'
        },
        {
            test:'Mu',
            str:'木'
        },
        {
            test:'Jin',
            str:'金'
        },
        {
            test:'Shui',
            str:'水'
        },
        {
            test:'Tu',
            str:'土'
        },
        {
            test:'name',
            str:'名字'
        },
        {
            test:'qiangruo',
            str:'强弱'
        },
        {
            test:'sex',
            str:'性别'
        },
        {
            test:'shui',
            str:'水'
        },
        {
            test:'taixi',
            str:'胎息'
        },
        {
            test:'taiyuan',
            str:'胎元'
        },
        {
            test:'tu',
            str:'土'
        },
        {
            test:'wuxing',
            str:'五行'
        },
        {
            test:'wxjishen',
            str:'五行忌神'
        },
        {
            test:'wxxishen',
            str:'五行喜神'
        },
        {
            test:'wxyongshen',
            str:'五行用神'
        },
        {
            test:'XiShen',
            str:'喜神'
        },
        {
            test:'yinyan',
            str:'阴阳'
        },
        {
            test:'yongshen',
            str:'用神'
        },
        {
            test:'yongshirenyuan',
            str:'用事人元'
        },
        {
            test:'yueling',
            str:'月令'
        },
        {
            test:'zaoshi',
            str:'燥湿'
        },
        {
            test:'zodiac',
            str:'生肖属相'
        },
        {
            test:'content',
            str:'性格'
        },
        {
            test:'Bazi',
            str:'八字'
        },
        {
            test:'CangGan',
            str:'长干'
        },
        {
            test:'DaYun',
            str:'大运'
        },
        {
            test:'DiZhi',
            str:'地支',
            toarr:','
        },
        {
            test:'DiZhiHeChong',
            str:'地支和冲'
        },
        {
            test:'FuXing',
            str:'副星',
            toarr:';'
        },
        {
            test:'GeJu',
            str:'格局'
        },
        {
            test:'Huo',
            str:'火'
        },
        {
            test:'JiShen',
            str:'机升'
        },
        {
            test:'JiaoYunShiJian',
            str:'交运时间'
        },
        {
            test:'Jin',
            str:'进'
        },
        {
            test:'Nian',
            str:'年'
        },
        {
            test:'NianGanZhi',
            str:'年干支'
        },
        {
            test:'Sui',
            str:'岁'
        },
        {
            test:'ChengGongYun',
            str:'成功运'
        },
        {
            test:'DiGe',
            str:'地格'
        },
        {
            test:'JiChuYun',
            str:'基础运'
        },
        // {
        //     test:'Ming',
        //     str:'名'
        // },
        {
            test:'Mings',
            str:'名'
        },
        {
            test:'PingFen',
            str:'评分'
        },
        {
            test:'RenGe',
            str:'人格'
        },
        {
            test:'SheJiaoYun',
            str:'社交运'
        },
        {
            test:'ShengYun',
            str:'声运'
        },
        {
            test:'TianGe',
            str:'天格'
        },
        {
            test:'WaiGe',
            str:'外格'
        },
        {
            test:'Xing',
            str:'姓'
        },
        {
            test:'Xings',
            str:'姓'
        },
        {
            test:'ZongGe',
            str:'总格'
        },
        {
            test:'ZongLun',
            str:'总论'
        },
        {
            test:'PingJian',
            str:'品鉴'
        },
        {
            test:'ShenShu',
            str:'生属'
        },
        {
            test:'WuHang',
            str:'五行'
        },
        {
            test:'WuXing',
            str:'五行'
        },
        {
            test:'ZuoShanWuHang',
            str:'坐山五行'
        },
        {
            test:'ZuoShan',
            str:'坐山'
        }

    ]
}